spring:
  profiles:
    active: "local"
  application:
    name: identity-service

server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: local

gcp:
  identity:
    apiKey: ${apiKey:AIzaSyC2xEH7CO8v6id73LoGxqguhaNyYam-zbA}
    authDomain: ${authDomain:ringed-spot-316103.firebaseapp.com}
    endpoint: https://identitytoolkit.googleapis.com/v2/
    project: ${project:ringed-spot-316103}

---
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#gcp:
#  identity:
#    apiKey:
#    authDomain:
